### ISSUE TITLE
Getting "scene_info" file.

### ISSUE THREAD

**Issue by Youyi7** [mihaidusmanu/d2-net#10]
Hey, could you please give me a download link which can get the "scene_info" file directly, I know it's a part of megadepth, but I just failed to download this data set, I have tried many times. 

It will be very nice if you can give the link :)

Thanks!

**Comment by mihaidusmanu** [comment]
The `scene_info` folder is **not sufficient** for fine-tuning the network - you will still need to download the full MegaDepth dataset for the raw images and depth-maps (~1TB). This folder only aggregates the SfM information in a more compact form so that it is faster to generate random training pairs.

Once you've downloaded MegaDepth, the `scene_info` folder can be generated by running the scripts from https://github.com/mihaidusmanu/d2-net/tree/master/megadepth_utils as described in the README.

Here is all the information required for the first scene of MegaDepth only - https://drive.google.com/open?id=1Tlkbr-bD1SOOPu_sshAotNTE7EKdw_aZ. `0000.0.npz` contains the scene information and the other 2 files contain the SfM reconstruction + raw images and MVS estimated depth respectively.

**Comment by Youyi7** [comment]
> The `scene_info` folder is **not sufficient** for fine-tuning the network - you will still need to download the full MegaDepth dataset for the raw images and depth-maps (~1TB). This folder only aggregates the SfM information in a more compact form so that it is faster to generate random training pairs.
> 
> Once you've downloaded MegaDepth, the `scene_info` folder can be generated by running the scripts from https://github.com/mihaidusmanu/d2-net/tree/master/megadepth_utils as described in the README.
> 
> Here is all the information required for the first scene of MegaDepth only - https://drive.google.com/open?id=1Tlkbr-bD1SOOPu_sshAotNTE7EKdw_aZ. `0000.0.npz` contains the scene information and the other 2 files contain the SfM reconstruction + raw images and MVS estimated depth respectively.

Perfect, thanks a lot ! ! !

**Comment by mihaidusmanu** [comment]
Hello. There was a small update to the training dataset that makes the correspondences more accurate. Please refer to the updated README for more information regarding the preprocessing procedure. I will close this issue, but feel free to open a new one in case you run into any issues.

**Comment by Mona77** [comment]
> Once you've downloaded MegaDepth, the `scene_info` folder can be generated by running the scripts from https://github.com/mihaidusmanu/d2-net/tree/master/megadepth_utils as described in the README.
> 
> Here is all the information required for the first scene of MegaDepth only - https://drive.google.com/open?id=1Tlkbr-bD1SOOPu_sshAotNTE7EKdw_aZ. `0000.0.npz` contains the scene information and the other 2 files contain the SfM reconstruction + raw images and MVS estimated depth respectively.

I'm trying to use the **0000.0.npz** scene.info that you have provided to get myself familiarized with the dataset. I get this error when I call `build_dataset` in [this line](https://github.com/mihaidusmanu/d2-net/blob/master/train.py#L234)

```
KeyError: 'points3D_id_to_ndepth is not a file in the archive'
```

**Comment by mihaidusmanu** [comment]
Hello. This is expected. The scene info file I provided here is for an older version of the code (and lacks some fields). The scene info files need to be regenerated with the updated scripts. I will make the files unavailable on drive so that there's no confusion.

**Comment by orsic** [comment]
Hello.

Thank you for the interesting work and provided code.
I was wondering what happened to the Google Drive link? It seems to be broken at the moment.

Best regards
