### ISSUE TITLE
About Hpatches

### ISSUE THREAD

**Issue by shamangary** [mihaidusmanu/d2-net#19]
Hello. Just want to ask the Hpatches eval. In the file there are
```
n_i=52
n_v=56
```
But I count the dataset and it seems like
```
n_i=57
n_v=59
```
Is there something I missed? Thanks

**Comment by mihaidusmanu** [comment]
Hello,

As mentioned in the paper, we have removed the sequences with high resolution images since some methods ran out of memory on them. The names of the removed sequences can be found below: 

https://github.com/mihaidusmanu/d2-net/blob/cc519c12c53e4b3a97afc8f5e3303ee08356a309/hpatches_sequences/download.sh#L11

By doing so, we ran all methods on the full-resolution images in order to avoid any bias in our evaluation (all methods had exactly the same image as input).

**Comment by shamangary** [comment]
Thank you for your quick reply.

There is another question. I went through the code and see the y-axis of MMA is (number of matches)/(number of image pairs). It seems like the y-lim is not really [0,1] correct? It is possible that the y-axis has val>1. Calling it mean matching accuracy implies that the boundaries are [0,1]. Can you clear this for me? Thanks a lot.

**Comment by mihaidusmanu** [comment]
The boundary is [0, 1] and we are reporting the mean matching accuracy (i.e. the average % of correct matches for each threshold). After the evaluation loop, `i_err` and `v_err` contain, for each threshold, the sum of percentages of correct matches over all the image pairs (```i_err[thr] += np.mean(dist <= thr)``` - the mean is between 0 and 1 and represents the % of correct matches for the current image pair). In the end, we simply divide this sum by the total number of image pairs.

**Comment by shamangary** [comment]
Ah~you ar right. I miss the np.mean. Thank you again. :)
