### ISSUE TITLE
About the speed in feature extraction process

### ISSUE THREAD

**Issue by shamangary** [mihaidusmanu/d2-net#2]
Hello, great paper.
Just want to ask about the feature extraction speed.
I try to extract d2-net feature in Aachen day-night dataset.
However, it takes about around 20~30 secs per image, even with the multi-scale option is off.
I wonder is it normal to observe such phenomenon? 
After tracing the code, it seems like the problem could be caused by the feature interpolation.
Do you have any comment on these things? Thanks.

**Comment by mihaidusmanu** [comment]
Hello! This is definitely not normal - the single-scale runtime on a GTX1080Ti is around 1 second and 3-4 seconds for multi-scale on a Tesla P100 16GB.

Are you running it on the GPU? If yes, what kind of GPU? What version of PyTorch /  CUDA / cuDNN are you using? I know there are some issues with dilated convolutions in the latest versions of PyTorch (which is why I suggested to use the CUDA 8 PyTorch 1.0 release). However, I personally never had any issues with the feature interpolation.

**Comment by shamangary** [comment]
Hello @mihaidusmanu, 

Thanks for the clarification. I setup the system again and the speed now is around 1 sec per image which is consistent to yours. Thank you again.
