### ISSUE TITLE
Performance of trained model weights

### ISSUE THREAD

**Issue by a1302z** [mihaidusmanu/d2-net#21]
Hi, 
thanks for making your code public.
I was wondering if there are performance stats to the trained model weights you offer? Would be great for deciding which weights to use for experiments.

**Comment by mihaidusmanu** [comment]
Hello. 

`d2_ots.pth` are simply the off-the-shelf Caffe weights pretrained on ImageNet. By default, at the moment, you should use the model fine-tuned on the entire MegaDepth - `d2_tf.pth` (i.e. the one used by the feature extraction - `extract_features.py` - script with default parameters). The model fine-tuned without the PhotoTourism scenes was only released in order to have a fair comparison on the Image Matching Workshop Benchmark - https://image-matching-workshop.github.io/. We plan on releasing new models in the future and we will include a more detailed comparison at that point in time.

**Comment by a1302z** [comment]
Thanks for the detailed answer.
