### ISSUE TITLE
hello,i want to ask what the mean of the path 'phoenix/S6/zl548/MegaDepth_v1' mentioned in undistort_reconstructions.py,i can't find this path in the megadepth_v1_sfm dataset 

### ISSUE THREAD

**Issue by liwenwei123** [mihaidusmanu/d2-net#24]

**Comment by mihaidusmanu** [comment]
Hello. The folder you mentioned contains the output of MVS (called MegaDepth v1 Dataset on the MegaDepth [website](http://www.cs.cornell.edu/projects/megadepth/)). It is needed for the undistortion step because different `--max_image_size` parameters were used during COLMAP MVS depending on the scenes - we need access to the MegaDepth undistorted images to infer this parameter.

**Comment by liwenwei123** [comment]
Thank you for the reply!I downloaded the MegaDepth v1 Dataset and found the folder!
