### ISSUE TITLE
Why the MMA is so low when threshold lower than 4px?

### ISSUE THREAD

**Issue by forrestl111** [mihaidusmanu/d2-net#48]
In Figure 4 of your paper, we can see that the trained D2-Net have low MMA when the threshold is small? It seems strange since it's even performs worse than the not trained version.

**Comment by mihaidusmanu** [comment]
That's in part expected since the description / detection is trained coarsely (grid with stride 8), due to the max-poolings in the VGG network. The features are detected with a spatial stride of 4 / 8 px - test / train. An error of 4px means exactly one pixel off (at test feature map resolution) without the order-2 keypoint refinement (which is not considered during training).
