### ISSUE TITLE
About the speed in feature extraction process?

### ISSUE THREAD

**Issue by ahong007007** [mihaidusmanu/d2-net#49]
Thank you so much for your perfect work。

Multi-scale feature extraction requires 12G of memory.4-5 seconds on a M40。
1.8w feature vector, it takes 20s for GPU to match。
How to reduce the memory and speed up the process of feature extraction and matching? Thank you！

**Comment by tongpinmo** [comment]
@ahong007007  have you ever solved this problem?

**Comment by mihaidusmanu** [comment]
Hello. Sorry for the late reply. The feature extraction time and memory for multi-scale sounds reasonable (on 1080Ti-s was ~4 seconds if I recall correctly for 1200x1600). This is mainly due to the upscaling of input image (octave -1). You can remove octave -1, but I never ran a large-scale evaluation without it so I don't know how it will impact performance. This can be done by removing the `2` in `scales` on the following line:
https://github.com/mihaidusmanu/d2-net/blob/81983664d1a29fabf09636b3735c5df9151db600/lib/pyramid.py#L9

The matching speed doesn't seem right: simple PyTorch implementation should be at least sub-second (e.g. the one from https://github.com/tsattler/visuallocalizationbenchmark/blob/master/local_feature_evaluation/matchers.py). What matcher are you using? What kind of images / how many features per image?
