### ISSUE TITLE
SfM 3D reconstruction dataset

### ISSUE THREAD

**Issue by GabbySuwichaya** [mihaidusmanu/d2-net#55]
Hi @mihaidusmanu. Thanks so much for the awesome work and papers. So far it works so well. 
Your work is one of  the famous works created in CVPR 2019.

Here, I would like to ask for some helps in setting a similar experiment to Table 1 in your paper. 

I have tried to do 3D reconstruction using D2-net features on the datasets provided in Table 1: Evaluation on the Local Feature Evaluation Benchmark in the paper.

Initially, I thought that the datasets were downloaded from https://research.cs.cornell.edu/1dsfm/ but it seems that this dataset is too difficult, so I could not get any results... 

Could you provide the source (website/links) to the internet data sets (Tower of London, Madrid Metropolis, Gendarmen market)?  As well as how you set the camera...? 

So far, I found that COLMAP spent so much time to find initialized points with D2-Net features, which could be because I didn't aware of all the settings that are suitable for D2-Net.

**Comment by mihaidusmanu** [comment]
Hello. The datasets can be downloaded from the benchmark page https://github.com/ahojnnes/local-feature-evaluation (see `INSTRUCTIONS.md` for the links and how to run details). I simply ran the toolkit available at that link. The only modification I did for D2-Net MS (Trained) was require more minimum matches during the COLMAP mapping in order to filter out wrongly matched pairs (by adding `--Mapper.min_num_matches 50` to the `mapper` call at line 175 in `scripts/reconstruction_pipeline.py`). As mentioned in the paper, don't forget to use ratio test (0.95 for trained D2-Net).

**Comment by GabbySuwichaya** [comment]
Hello @mihaidusmanu. Thanks so much for the prompt reply. 

I do really appreciate your help; I almost get it here, but I still have a few more questions.  

I have downloaded and tried to use the **local-feature-evaluation** package with D2-Net.  

In https://github.com/ahojnnes/local-feature-evaluation, a MATLAB script: [matching_pipeline.m](https://github.com/ahojnnes/local-feature-evaluation/blob/master/scripts/matching_pipeline.m) is called to perform exhaustive matching. 

I wonder whether you use the default parameters in this file such as ..... 
PATCH_RADIUS = 32,  MATCH_BLOCK_SIZE = 50;
MATCH_MAX_DIST_RATIO = 0.8;  ..... ( _Is this one changed to 0.95 ?_....) 
MIN_NUM_MATCHES = 15; 

Also, did you use the _PATCH_RADIUS_ at all? 

It seems that there are 2 possible options to get the extracted D2-Net here. 

One way is simply import the extracted features from D2-Net and apply them to the database. Did you just _import_ the extract features? 

Or, another way is to use the provided matlab script [feature_extraction_example.m](https://github.com/ahojnnes/local-feature-evaluation/blob/master/scripts/feature_extraction_example.m) in this package.

**Comment by mihaidusmanu** [comment]
Hello. I simply saved the D2-Net features to binary files (see https://github.com/ahojnnes/local-feature-evaluation/blob/master/scripts/feature_extraction_lift.py for an example) and then used the `matching_pipeline.m` with `MATCH_MAX_DIST_RATIO=0.95` for exhaustive matching. The rest of the parameters for matching were left at their default values since they are only used for patch descriptors such as TFeat / HardNet. 

To sum it up, here are the subsequent steps:
1. Run D2-Net feature extraction and save the output to binary files as it is done for LIFT.
2. Run `matching_pipeline.m` for matching (after changing the paths to the appropriate ones and setting `MATCH_MAX_DIST_RATIO=0.95`). You will also need to comment out `feature_extraction` in L79 since this was already done in step 1.
3. Run `reconstruction_pipeline.py`.

Let me know if you run into any troubles!

**Comment by GabbySuwichaya** [comment]
Thanks, it's all done. :)
