### ISSUE TITLE
bash preprocess_megadepth.sh runtime warning

### ISSUE THREAD

**Issue by pmwenzel** [mihaidusmanu/d2-net#6]
I am trying to preprocess the megadepth dataset. However, by running the bash script I get a lot of RuntimeWarnings. Is this normal?

`0004
0005
0007
0008
preprocess_scene.py:158: RuntimeWarning: invalid value encountered in arccos
  angles = np.arccos(np.dot(principal_axis, np.transpose(principal_axis))) / np.pi * 180
preprocess_scene.py:158: RuntimeWarning: invalid value encountered in arccos
  angles = np.arccos(np.dot(principal_axis, np.transpose(principal_axis))) / np.pi * 180
preprocess_scene.py:158: RuntimeWarning: invalid value encountered in arccos
  angles = np.arccos(np.dot(principal_axis, np.transpose(principal_axis))) / np.pi * 180
0011
preprocess_scene.py:158: RuntimeWarning: invalid value encountered in arccos
  angles = np.arccos(np.dot(principal_axis, np.transpose(principal_axis))) / np.pi * 180
0012
`

Thanks

**Comment by mihaidusmanu** [comment]
Nothing to worry about. The warning is due to some numerical errors when computing the dot product (values outside of [-1, 1]). A possible fix would be to clip the values - I will do this in a future commit. 

Somehow related - I will release an updated training code that will probably yield better performance than the current one. It should be ready by next week (in case everything goes well).

**Comment by pmwenzel** [comment]
Thanks! Looking forward to the updated code :)

**Comment by mihaidusmanu** [comment]
The latest commit should (among other things) fix the warnings you were having when preprocessing the dataset. For the best performance, I suggest you preprocess the dataset again using the new script!
