### ISSUE TITLE
HPatches evaluation by SuperPoint and RootSIFT

### ISSUE THREAD

**Issue by coper16** [mihaidusmanu/d2-net#74]
Hi!
Thank you for your great work!

I want to use your HPatches evaluation code.
but, I cannot understand how to apply SuperPointNet and RootSIFT to this.
(for example, SuperPointNet outputs Keypoint and descriptor. But, d2-net(model_test.py) outputs dense_feature,detections,and displacement.)

Could you tell me how to apply SuperPoint and RootSIFT to feature extraction code(extract_features.py,model_test.py and pyramid.py)?

**Comment by mihaidusmanu** [comment]
You should not use `model_test.py` since that is only an internal class. You should use `extract_features.py` which directly returns keypoints and descriptors as explained at the following link https://github.com/mihaidusmanu/d2-net#feature-extraction.

For the HPatches code, there are instructions on running it in the associated folder: https://github.com/mihaidusmanu/d2-net/tree/master/hpatches_sequences#hpatches-sequences--image-pairs-matching-benchmark. 

There is no code for SuperPoint in this repo, please refer to the official repository.
